package source

import (
	"github.com/gookit/color"
	"github.com/snowlyg/go-tenancy/g"
	"github.com/snowlyg/go-tenancy/model"

	"gorm.io/gorm"
)

var BaseMenu = new(menu)

type menu struct{}

var menus = []model.SysBaseMenu{
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 33}, Pid: 0, Path: "/", Icon: "s-home", MenuName: "仪表盘", Route: "/admin/dashboard", Params: "", Sort: 100, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 34}, Pid: 110, Path: "/110/", Icon: "", MenuName: "系统配置", Route: "/admin/config", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 35}, Pid: 34, Path: "/110/34/", Icon: "", MenuName: "配置分类", Route: "/admin/config/classify", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 36}, Pid: 34, Path: "/110/34/", Icon: "", MenuName: "配置管理", Route: "/admin/config/setting", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 38}, Pid: 110, Path: "/110/", Icon: "", MenuName: "权限管理", Route: "/admin/setting", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 39}, Pid: 38, Path: "/110/38/", Icon: "", MenuName: "角色管理", Route: "/admin/setting/systemRole", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 40}, Pid: 38, Path: "/110/38/", Icon: "", MenuName: "员工管理", Route: "/admin/setting/systemAdmin", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 41}, Pid: 34, Path: "/110/34/", Icon: "", MenuName: "素材管理", Route: "/admin/config/picture", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 42}, Pid: 0, Path: "/", Icon: "s-shop", MenuName: "商户", Route: "/admin/merchant", Params: "", Sort: 94, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 43}, Pid: 42, Path: "/42/", Icon: "", MenuName: "商户菜单管理", Route: "/admin/merchant/system", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 44}, Pid: 42, Path: "/42/", Icon: "", MenuName: "商户列表", Route: "/admin/merchant/list", Params: "", Sort: 9, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 47}, Pid: 38, Path: "/110/38/", Icon: "", MenuName: "操作日志", Route: "/admin/setting/systemLog", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 48}, Pid: 38, Path: "/110/38/", Icon: "", MenuName: "菜单管理", Route: "/admin/setting/menu", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},

	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 49}, Pid: 526, Path: "/526/", Icon: "", MenuName: "权限管理", Route: "/merchant/setting", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 50}, Pid: 49, Path: "/526/49/", Icon: "", MenuName: "角色管理", Route: "/merchant/setting/systemRole", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 51}, Pid: 49, Path: "/526/49/", Icon: "", MenuName: "员工管理", Route: "/merchant/setting/systemAdmin", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 52}, Pid: 49, Path: "/526/49/", Icon: "", MenuName: "操作日志", Route: "/merchant/setting/systemLog", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 54}, Pid: 526, Path: "/526/", Icon: "", MenuName: "素材管理", Route: "/merchant/config/picture", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 55}, Pid: 0, Path: "/", Icon: "s-home", MenuName: "首页", Route: "/merchant/dashboard", Params: "", Sort: 100, Hidden: 2, IsTenancy: 1, IsMenu: 1},

	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 57}, Pid: 521, Path: "/520/521/", Icon: "", MenuName: "组合数据", Route: "/admin/group/list", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 58}, Pid: 519, Path: "/519/", Icon: "", MenuName: "公众号", Route: "/admin/app/wechat", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 59}, Pid: 58, Path: "/519/58/", Icon: "", MenuName: "微信菜单", Route: "/admin/app/wechat/menus", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 60}, Pid: 0, "/", "s-management", "文章", "/cms", "", 96,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 61}, Pid: 60, "/60/", "", "文章管理", "/cms/article", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 62}, Pid: 60, "/60/", "", "文章分类", "/cms/articleCategory", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 63}, Pid: 110, Path: "/110/", Icon: "", MenuName: "商城配置", Route: "/admin/system", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 64}, Pid: 63, Path: "/110/63/", Icon: "", MenuName: "基础配置", Route: "/admin/systemForm/Basics/base", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 68}, Pid: 63, Path: "/110/63/", Icon: "", MenuName: "商城配置", Route: "/admin/systemForm/Basics/shop", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 72}, Pid: 111, Path: "/110/111/", Icon: "", MenuName: "短信配置", Route: "/admin/systemForm/Basics/message", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 74}, Pid: 526, Path: "/526/", Icon: "", MenuName: "店铺配置", Route: "/merchant/systemForm/Basics/mer_base", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 77}, Pid: 58, Path:  "/519/58/",Icon: "",MenuName: "自动回复",Route: "/admin/app/wechat/reply", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 79}, Pid: 77,  Path: "/519/58/77/",Icon: "", MenuName:"微信关注回复",Route: "/app/wechat/reply/follow/subscribe", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 80}, Pid: 77, "/519/58/77/", "", "关键字回复", "/app/wechat/reply/keyword", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 81}, Pid: 77, "/519/58/77/", "", "无效关键词回复", "/app/wechat/reply/index/default", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 82}, Pid: 58, "/519/58/", "", "图文管理", "/app/wechat/newsCategory", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 87}, Pid: 0, Path: "/", Icon: "s-goods", MenuName: "商品", Route: "/product", Params: "", Sort: 99, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 88}, Pid: 87, Path: "/87/", Icon: "", MenuName: "商品分类", Route: "/admin/product/classify", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 92}, Pid: 87, Path: "/87/", Icon: "", MenuName: "品牌管理", Route: "/admin/product/brand", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 93}, Pid: 92, Path: "/87/92/", Icon: "", MenuName: "品牌分类", Route: "/admin/product/band/brandClassify", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 94}, Pid: 92, Path: "/87/92/", Icon: "", MenuName: "品牌列表", Route: "/admin/product/band/brandList", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 95}, Pid: 0, Path: "/", Icon: "s-goods", MenuName: "商品", Route: "/merchant/product", Params: "", Sort: 99, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 96}, Pid: 95, Path: "/95/", Icon: "", MenuName: "商品分类", Route: "/merchant/product/classify", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 99}, Pid: 95, Path: "/95/", Icon: "", MenuName: "商品规格", Route: "/merchant/product/attr", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 100}, Pid: 42, "/42/", "", "商户分类", "/merchant/classify", "", 10,Hidden: 2, IsTenancy:2,IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 101}, Pid: 0, Path: "/", Icon: "user-solid", MenuName: "用户", Route: "/admin/user", Params: "", Sort: 96, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 102}, Pid: 101, Path: "/101/", Icon: "", MenuName: "用户分组", Route: "/admin/user/group", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 103}, Pid: 101, Path: "/101/", Icon: "", MenuName: "用户列表", Route: "/admin/user/list", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 104}, Pid: 101, Path: "/101/", Icon: "", MenuName: "用户标签", Route: "/admin/user/label", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 105}, Pid: 95, Path: "/95/", Icon: "", MenuName: "商品列表", Route: "/merchant/product/list", Params: "", Sort: 2, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 106}, Pid: 0, Path: "/", Icon: "orange", MenuName: "营销", Route: "/merchant/marketing", Params: "", Sort: 97, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 107}, Pid: 106, Path: "/106/", Icon: "", MenuName: "优惠券", Route: "/merchant/marketing/coupon", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 110}, Pid: 0, Path: "/", Icon: "s-tools", MenuName: "设置", Route: "/merchant/settings", Params: "", Sort: 92, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 111}, Pid: 110, Path: "/110/", Icon: "", MenuName: "短信设置", Route: "/sms", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 112}, Pid: 111, "/110/111/", "", "短信账户", "/sms/config", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 113}, Pid: 111, "/110/111/", "", "短信模板", "/sms/template", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 114}, Pid: 111, "/110/111/", "", "短信购买", "/sms/pay", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 115}, Pid: 107, Path: "/106/107/", Icon: "", MenuName: "优惠券列表", Route: "/merchant/marketing/coupon/list", Params: "", Sort: 1, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 116}, Pid: 520, "/520/", "", "安全维护", "/maintain", "", 9,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 117}, Pid: 116, "/520/116/", "", "数据备份", "/maintain/dataBackup", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 118}, Pid: 110, Path: "/110/", Icon: "", MenuName: "物流管理", Route: "/admin/freight", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 119}, Pid: 118, Path: "/110/118/", Icon: "", MenuName: "物流公司", Route: "/admin/freight/express", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 120}, Pid: 526, Path: "/526/", Icon: "", MenuName: "客服管理", Route: "/merchant/config/service", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 121}, Pid: 87, Path: "/87/", Icon: "", MenuName: "评论管理", Route: "/admin/product/comment", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 122}, Pid: 107, Path: "/106/107/", Icon: "", MenuName: "会员领取记录", Route: "/merchant/marketing/coupon/user", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},

	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 466}, Pid: 101, Path: "/101/", Icon: "", MenuName: "用户反馈", Route: "/admin/feedback", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 467}, Pid: 466, Path: "/101/466/", Icon: "", MenuName: "反馈分类", Route: "/admin/feedback/classify", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 468}, Pid: 466, Path: "/101/466/", Icon: "", MenuName: "反馈列表", Route: "/admin/feedback/list", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},

	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 512}, Pid: 0, Path: "/", Icon: "s-order", MenuName: "订单", Route: "/merchant/order", Params: "", Sort: 99, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 513}, Pid: 512, Path: "/512/", Icon: "", MenuName: "订单管理", Route: "/merchant/order/list", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 514}, 0, "/", "s-flag", "分销", "/promoter", "", 97,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 515}, 0, "/", "s-data", "财务", "/accounts", "", 95,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 516}, 515, "/515/", "", "提现管理", "/accounts/extract", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 517}, 537, "/515/537/", "", "充值记录", "/accounts/bill", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 518}, 515, "/515/", "", "财务对账", "/accounts/reconciliation", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 519}, 0, "/", "s-grid", "应用", "/apploction", "", 93,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 520}, 0, "/", "s-help", "维护", "/safe", "", 91,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 521}, 520, "/520/", "", "开发配置", "/safe/exploit", "[]", 10,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 522}, 514, "/514/", "", "分销员列表", "/promoter/user", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 523}, 514, "/514/", "", "分销配置", "/promoter/config", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 524}, 519, "/519/", "", "小程序", "/app/routine", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 525}, Pid: 0, Path: "/", Icon: "s-data", MenuName: "财务", Route: "/merchant/accounts", Params: "", Sort: 97, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 526}, Pid: 0, Path: "/", Icon: "s-tools", MenuName: "设置", Route: "/merchant/config", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 528}, Pid: 512, Path: "/512/", Icon: "", MenuName: "退款单", Route: "/merchant/order/refund", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 532}, 58, "/519/58/", "", "微信模板消息", "/app/wechat/template", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 536}, 42, "/42/", "", "商户对账", "/merchant/list/record/:id?", "", 0, 0, 0, 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 537}, 515, "/515/", "", "财务记录", "/accounts/record", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 538}, 537, "/515/537/", "", "资金记录", "/accounts/capital", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 539}, Pid: 87, Path: "/87/", Icon: "", MenuName: "商品管理", Route: "/admin/product/examine", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 540}, Pid: 0, Path: "/", Icon: "s-cooperation", MenuName: "订单管理", Route: "/admin/order", Params: "", Sort: 98, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 541}, Pid: 540, Path: "/540/", Icon: "", MenuName: "订单列表", Route: "/admin/order/list", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 542}, Pid: 540, Path: "/540/", Icon: "", MenuName: "退款单", Route: "/admin/order/refund", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 543}, Pid: 525, Path: "/525/", Icon: "", MenuName: "财务对账", Route: "/merchant/accounts/reconciliation", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 544}, Pid: 95, Path: "/95/", Icon: "", MenuName: "商品评价", Route: "/merchant/product/reviews", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 545}, 524, "/519/524/", "", "小程序订阅消息", "/app/routine/template", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 546}, Pid: 526, Path: "/526/", Icon: "", MenuName: " 基础配置", Route: "/merchant/systemForm/modifyStoreInfo", Params: "", Sort: 1, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 666}, 116, "/520/116/", "", "商业授权", "/maintain/auth", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 667}, Pid: 63, Path: "/110/63/", Icon: "", MenuName: "余额/充值设置", Route: "/admin/systemForm/Basics/balance", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 668}, Pid: 63, Path: "/110/63/", Icon: "", MenuName: "文件上传", Route: "/admin/systemForm/Basics/upload", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 669}, Pid: 110, Path: "/110/", Icon: "", MenuName: "支付配置", Route: "/admin/pay_config", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 670}, Pid: 110, Path: "/110/", Icon: "", MenuName: "应用配置", Route: "/admin/app_config", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 671}, Pid: 669, Path: "/110/669/", Icon: "", MenuName: "公众号支付配置", Route: "/admin/systemForm/Basics/wechat_payment", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 672}, Pid: 669, Path: "/110/669/", Icon: "", MenuName: "小程序支付配置", Route: "/admin/systemForm/Basics/routine_pay", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 673}, Pid: 670, Path: "/110/670/", Icon: "", MenuName: "公众号配置", Route: "/admin/systemForm/Basics/wechat", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 674}, Pid: 670, Path: "/110/670/", Icon: "", MenuName: "小程序配置", Route: "/admin/systemForm/Basics/smallapp", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 676}, Pid: 514, Path: "/514/", Icon: "", MenuName: "相关配置", Route: "/admin/systemForm/Basics/brokerage", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 677}, 514, "/514/", "", "提现银行管理", "/promoter/bank/76", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 678}, 110, "/110/", "", "页面设置", "/page_setting", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 679}, 678, "/110/678/", "", "首页幻灯片", "/promoter/bank/72", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 680}, 678, "/110/678/", "", "首页导航按钮", "/promoter/bank/73", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 681}, 678, "/110/678/", "", "首页推荐区", "/promoter/bank/74", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 682}, 678, "/110/678/", "", "个人中心幻灯片", "/promoter/bank/71", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 683}, 678, "/110/678/", "", "个人中心菜单", "/promoter/bank/70", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 684}, 678, "/110/678/", "", "热门搜索", "/promoter/bank/67", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 685}, 678, "/110/678/", "", "分销特权", "/promoter/bank/75", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 686}, 678, "/110/678/", "", "分销海报", "/promoter/bank/68", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 687}, 678, "/110/678/", "", "充值金额配置", "/promoter/bank/69", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 688}, 63, "/110/63/", "", "登录页幻灯片", "/promoter/bank/77", Params: "", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 700}, Pid: 526, Path: "/526/", Icon: "", MenuName: "运费模板", Route: "/merchant/config/freight/shippingTemplates", Params: "", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},

	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 719}, 0, "/", "help", "营销", "/marketing", Params:"[]",Sort: 97, Hidden:1,IsTenancy: 0,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 720}, 719, "/719/", "", "优惠券", "/marketing/coupon",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 721}, 720, "/719/720/", "", "优惠券列表", "/marketing/coupon/list",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 731}, 514, "/514/", "", "分销礼包", "/promoter/gift",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 734}, 720, "/719/720/", "", "会员领取记录", "/marketing/coupon/user",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 778}, 42, "/42/", "", "商户入驻申请", "/merchant/application",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 779}, 780, "/719/780/", "", "秒杀配置", "/marketing/seckill/seckillConfig",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 780}, 719, "/719/", "", "秒杀", "/marketing/seckill",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 781}, 782, "/719/782/", "", "直播间管理", "/marketing/studio/list",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 782}, 719, "/719/", "", "直播", "/marketing2",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 783}, 782, "/719/782/", "", "直播商品管理", "/marketing/broadcast/list",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 784}, Pid: 540, Path: "/540/", Icon: "", MenuName: "核销订单", Route: "/admin/order/cancellation", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 785}, Pid: 106, Path: "/106/", Icon: "", MenuName: "直播", Route: "/", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 786}, Pid: 785, Path: "/106/785/", Icon: "", MenuName: "直播间管理", Route: "/merchant/marketing/studio/list", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 787}, Pid: 785, Path: "/106/785/", Icon: "", MenuName: "直播商品管理", Route: "/merchant/marketing/broadcast/list", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 788}, Pid: 106, Path: "/106/", Icon: "", MenuName: "秒杀", Route: "/merchant/marketing/seckill/list", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 789}, Pid: 512, Path: "/512/", Icon: "", MenuName: "核销订单", Route: "/merchant/order/cancellation", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 790}, Pid: 525, Path: "/525/", Icon: "", MenuName: "资金流水", Route: "/merchant/accounts/capitalFlow", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 791}, 515, "/515/", "", "资金流水", "/accounts/capitalFlow",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 793}, Pid: 526, Path: "/526/", Icon: "", MenuName: "自提点设置", Route: "/merchant/systemForm/systemStore", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 794}, 780, "/719/780/", "", "秒杀管理", "/marketing/seckill/list",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},

	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1022}, 719, "/719/", "", "预售", "/marketing/presell",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1023}, 1022, "/719/1022/", "", "预售商品", "/marketing/presell/list",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1024}, 1022, "/719/1022/", "", "预售协议", "/marketing/presell/agreement",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1025}, Pid: 106, Path: "106/", Icon: "", MenuName: "预售", Route: "/merchant/marketing/presell/list", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1026}, Pid: 669, Path: "/110/669/", Icon: "", MenuName: "支付宝支付配置", Route: "/admin/systemForm/Basics/alipay", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1027}, Pid: 0, Path: "/", Icon: "user-solid", MenuName: "用户", Route: "/merchant/user", Params: "[]", Sort: 1, Hidden: 2, IsTenancy: 2, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1028}, Pid: 1027, Path: "1027/", Icon: "", MenuName: "标签管理", Route: "/merchant/user/_label", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1029}, Pid: 1028, Path: "1028/", Icon: "", MenuName: "手动标签", Route: "/merchant/user/label", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1030}, Pid: 1028, Path: "1028/", Icon: "", MenuName: "自动标签", Route: "/merchant/user/maticlabel", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},

	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1095}, 1051, "/719/1051/", "", "活动商品", "/marketing/assist/goods_list",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1096}, 1051, "/719/1051/", "", "助力活动", "/marketing/assist/list",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1099}, Pid: 106, Path: "106/", Icon: "", MenuName: "助力", Route: "/merchant/assist", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1100}, Pid: 1099, Path: "1099/", Icon: "", MenuName: "助力商品", Route: "/merchant/marketing/assist/list", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1101}, Pid: 1099, Path: "1099/", Icon: "", MenuName: "助力活动", Route: "/merchant/marketing/assist/assist_set", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1102}, Pid: 525, Path: "525/", Icon: "", MenuName: "发票管理", Route: "/merchant/order/invoice", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	{TENANCY_MODEL: g.TENANCY_MODEL{ID: 1103}, Pid: 1027, Path: "1027/", Icon: "", MenuName: "用户管理", Route: "/merchant/user/list", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1119}, Pid: 0, Path: "/", Icon: "message", MenuName: "公告列表", Route: "/merchant/station/notice", Params: "[]", Sort: 0, Hidden: 2, IsTenancy: 1, IsMenu: 1},
	// {TENANCY_MODEL: g.TENANCY_MODEL{ID: 1120}, 110, "/110/", "", "公告管理", "/station/notice",Params:  "[]", Sort: 0,Hidden: 2, IsTenancy:2,IsMenu: 1},
}

//Init sys_base_menus 表数据初始化
func (m *menu) Init() error {
	return g.TENANCY_DB.Transaction(func(tx *gorm.DB) error {
		if tx.Where("id IN ?", []int{1, 29}).Find(&[]model.SysBaseMenu{}).RowsAffected == 2 {
			color.Danger.Println("\n[Mysql] --> sys_base_menus 表的初始数据已存在!")
			return nil
		}
		if err := tx.Create(&menus).Error; err != nil { // 遇到错误时回滚事务
			return err
		}
		color.Info.Println("\n[Mysql] --> sys_base_menus 表初始数据成功!")
		return nil
	})
}
